-- Make ticket_number have a default value so it can be auto-generated by trigger
ALTER TABLE public.support_tickets 
ALTER COLUMN ticket_number SET DEFAULT '';

-- Drop the old trigger and create a new one that always sets ticket_number
DROP TRIGGER IF EXISTS trigger_set_ticket_number ON public.support_tickets;

CREATE OR REPLACE FUNCTION public.set_ticket_number()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.ticket_number := public.generate_ticket_number();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_set_ticket_number
  BEFORE INSERT ON public.support_tickets
  FOR EACH ROW
  EXECUTE FUNCTION public.set_ticket_number();