// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhcsvsgdexhqtlsblalw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoY3N2c2dkZXhocXRsc2JsYWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODQzMTEsImV4cCI6MjA2ODk2MDMxMX0.GA579YUrC8dAMECe5-cJG4XAUTPotDAjPZY_4wgutXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});